In [9]:
from sklearn.datasets import load_iris, fetch_openml
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder

In [ ]:
X, y=load_iris(return_X_y=True)
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.6, 1.4, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5. , 2.3, 3.3, 1. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

In [4]:
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.2)

In [ ]:
scaler=StandardScaler()
# take mean, std, variance from the sample and do calculations, to get trained data in a scaled way
X_train_scaled=scaler.fit_transform(X_train)
# fit transform: learning these value and do calculations
X_test_scaled=scaler.transform(X_test)
# just do tranform because use same calculations as before
"""
# zero centered the data and bring it to unit variance
(X_train - np.mean(X_train, axis=0))/np.std(X_train, axis=0)
"""
X_train_scaled

array([[ 2.26993576, -0.25863986,  1.36366852,  1.45442273],
       [ 0.6017415 , -1.89215477,  0.43171416,  0.19518227],
       [-0.35151236,  0.9081565 , -1.26773204, -1.18998223],
       [ 1.07836843, -0.02528059,  0.43171416,  0.32110632],
       [-0.82813929,  0.67479723, -1.15809035, -1.18998223],
       [ 0.6017415 , -0.72535841,  0.81546007,  0.44703036],
       [ 0.6017415 ,  0.67479723,  1.0895643 ,  1.58034678],
       [ 1.07836843,  0.44143796,  1.14438514,  1.20257464],
       [-0.94729603,  0.9081565 , -1.26773204, -1.06405819],
       [-0.23235563, -0.25863986,  0.26725162,  0.19518227],
       [-0.1131989 , -0.72535841,  0.486535  ,  0.19518227],
       [-1.06645276, -1.42543622,  0.486535  ,  0.69887846],
       [-0.23235563, -0.95871768,  0.32207247,  0.19518227],
       [-1.18560949, -0.25863986, -1.2129112 , -1.06405819],
       [ 0.6017415 , -1.42543622,  0.76063923,  0.95072655],
       [ 2.26993576, -1.19207695,  1.80223528,  1.45442273],
       [-0.94729603,  1.14151578, -1.2129112 , -1.18998223],
       [-0.94729603, -0.25863986, -1.10326951, -1.18998223],
       [-0.94729603,  0.9081565 , -1.10326951, -0.68628605],
       [-1.18560949,  0.67479723, -0.93880697, -1.18998223],
       [ 0.36342803, -1.19207695,  1.0895643 ,  0.32110632],
       [-0.82813929,  1.60823432, -0.93880697, -0.93813414],
       [ 0.2442713 ,  0.67479723,  0.486535  ,  0.57295441],
       [ 0.2442713 , -0.49199913,  0.486535  ,  0.44703036],
       [ 1.79330883, -0.49199913,  1.47331021,  0.8248025 ],
       [ 0.00595784,  2.07495287, -1.32255289, -1.18998223],
       [ 1.3166819 ,  0.20807868,  1.14438514,  1.45442273],
       [ 0.6017415 , -0.95871768,  0.70581838,  0.8248025 ],
       [-1.30476622,  0.20807868, -1.10326951, -1.18998223],
       [ 0.84005497,  0.20807868,  0.81546007,  1.07665059],
       [-0.47066909, -0.25863986,  0.486535  ,  0.44703036],
       [ 0.6017415 , -1.42543622,  0.70581838,  0.44703036],
       [ 1.07836843,  0.44143796,  1.14438514,  1.70627082],
       [-0.82813929,  1.37487505, -1.15809035, -0.93813414],
       [-0.23235563, -0.25863986,  0.486535  ,  0.44703036],
       [-0.94729603,  0.44143796, -1.2129112 , -1.18998223],
       [ 1.07836843, -0.02528059,  1.0895643 ,  1.58034678],
       [ 1.43583863,  0.20807868,  0.59617669,  0.32110632],
       [ 0.36342803, -0.72535841,  0.59617669,  0.06925823],
       [ 0.36342803, -0.72535841,  0.21243077,  0.19518227],
       [ 0.72089823,  0.20807868,  0.486535  ,  0.44703036],
       [ 1.19752516, -0.72535841,  0.65099754,  0.32110632],
       [-1.18560949, -0.25863986, -1.2129112 , -1.31590628],
       [ 1.19752516, -0.25863986,  1.03474345,  1.20257464],
       [ 0.12511457, -0.25863986,  0.81546007,  0.8248025 ],
       [ 1.3166819 , -0.02528059,  0.70581838,  0.44703036],
       [-0.1131989 ,  3.00838996, -1.15809035, -0.93813414],
       [ 0.2442713 , -0.25863986,  0.65099754,  0.8248025 ],
       [-0.47066909,  0.67479723, -1.15809035, -0.93813414],
       [ 0.2442713 , -2.12551404,  0.76063923,  0.44703036],
       [ 1.07836843, -0.02528059,  0.59617669,  0.44703036],
       [ 0.6017415 , -0.49199913,  1.0895643 ,  0.8248025 ],
       [-0.70898256,  2.30831214, -1.15809035, -1.31590628],
       [-0.47066909,  1.37487505, -1.15809035, -1.18998223],
       [ 0.12511457, -0.25863986,  0.32207247,  0.44703036],
       [-0.82813929,  0.44143796, -1.04844866, -0.8122101 ],
       [-0.94729603,  0.67479723, -1.10326951, -0.93813414],
       [ 2.15077903, -0.25863986,  1.63777275,  1.20257464],
       [ 0.84005497, -0.72535841,  0.54135585,  0.44703036],
       [ 0.48258477,  0.67479723,  0.97992261,  1.45442273],
       [ 1.07836843, -1.42543622,  1.19920599,  0.8248025 ],
       [-0.1131989 , -1.42543622,  0.76063923,  1.07665059],
       [ 1.55499536, -0.25863986,  1.25402683,  1.20257464],
       [-0.94729603, -1.89215477, -0.17131514, -0.18258987],
       [ 0.12511457,  0.20807868,  0.65099754,  0.8248025 ],
       [-0.94729603,  0.67479723, -1.15809035, -1.18998223],
       [-0.1131989 , -0.25863986,  0.32207247,  0.06925823],
       [-1.18560949, -0.02528059, -1.10326951, -1.18998223],
       [ 0.48258477, -0.72535841,  0.65099754,  0.8248025 ],
       [-1.78139315, -0.25863986, -1.37737373, -1.31590628],
       [-0.35151236, -1.6587955 ,  0.04796824, -0.18258987],
       [-1.66223642, -0.25863986, -1.26773204, -1.18998223],
       [-1.42392296,  0.67479723, -1.2129112 , -1.06405819],
       [ 0.72089823, -0.95871768,  0.92510176,  0.95072655],
       [ 0.36342803, -0.25863986,  0.70581838,  0.8248025 ],
       [ 1.07836843, -0.25863986,  0.87028092,  1.45442273],
       [-0.47066909,  0.67479723, -1.04844866, -1.18998223],
       [ 1.3166819 , -0.02528059,  0.97992261,  1.20257464],
       [ 0.36342803, -0.25863986,  0.54135585,  0.32110632],
       [ 0.84005497, -0.25863986,  0.87028092,  1.07665059],
       [-0.82813929,  1.60823432, -1.10326951, -1.18998223],
       [-1.66223642, -0.49199913, -1.2129112 , -1.18998223],
       [ 0.00595784, -0.95871768,  0.81546007,  0.95072655],
       [-0.94729603, -2.59223259, -0.06167345, -0.18258987],
       [-0.70898256,  0.9081565 , -1.15809035, -1.18998223],
       [-1.06645276,  1.14151578, -1.2129112 , -1.31590628],
       [-0.47066909,  1.84159359, -1.04844866, -0.93813414],
       [ 2.50824922,  1.60823432,  1.52813106,  1.07665059],
       [ 0.84005497, -0.25863986,  1.19920599,  1.32849869],
       [-0.1131989 , -0.72535841,  0.26725162,  0.19518227],
       [ 0.9592117 , -0.49199913,  0.54135585,  0.19518227],
       [-1.66223642,  0.20807868, -1.26773204, -1.18998223],
       [ 1.6741521 ,  1.14151578,  1.36366852,  1.70627082],
       [-1.42392296,  0.20807868, -1.2129112 , -1.18998223],
       [-1.06645276, -0.02528059, -1.15809035, -1.31590628],
       [-0.35151236,  2.54167141, -1.2129112 , -1.18998223],
       [ 0.6017415 ,  0.44143796,  1.30884768,  1.70627082],
       [ 1.6741521 ,  0.20807868,  1.30884768,  0.8248025 ],
       [-0.35151236, -1.6587955 ,  0.10278908, -0.05666582],
       [-0.47066909,  1.84159359, -1.26773204, -0.93813414],
       [-1.42392296, -0.02528059, -1.15809035, -1.18998223],
       [-0.1131989 ,  1.60823432, -1.04844866, -1.06405819],
       [-1.30476622,  0.20807868, -1.26773204, -1.18998223],
       [ 0.72089823, -0.72535841,  1.0895643 ,  1.32849869],
       [-1.06645276, -0.02528059, -1.15809035, -1.18998223],
       [ 1.19752516,  0.20807868,  1.25402683,  1.45442273],
       [-1.42392296,  1.14151578, -1.43219458, -1.18998223],
       [ 0.00595784, -0.95871768,  0.81546007,  0.95072655],
       [-0.70898256, -0.95871768,  0.15760993,  0.32110632],
       [-0.58982583,  1.37487505, -1.15809035, -1.18998223],
       [-0.35151236, -1.19207695,  0.43171416,  0.06925823],
       [-0.82813929,  0.9081565 , -1.2129112 , -1.18998223],
       [-0.82813929,  0.9081565 , -1.2129112 , -1.06405819],
       [-1.06645276, -0.25863986, -1.2129112 , -1.18998223],
       [-0.23235563, -1.42543622,  0.15760993, -0.05666582],
       [ 1.3166819 , -0.02528059,  0.81546007,  1.45442273],
       [-0.35151236, -1.42543622,  0.21243077,  0.19518227],
       [ 1.6741521 , -0.25863986,  1.19920599,  0.57295441],
       [-0.94729603,  0.20807868, -1.32255289, -1.18998223],
       [-1.18560949,  0.67479723, -1.10326951, -1.18998223]])

In [ ]:
scaler=MinMaxScaler()
# similiar to standard scaler, but press all the value to be 0-1
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)
X_train_scaled
"""
X_min=np.min(X_train, axis=0)
X_max=np.max(X_train, axis=0)
(X_train - X_min)/(X_max - X_min)
"""

array([[0.94444444, 0.41666667, 0.86440678, 0.91666667],
       [0.55555556, 0.125     , 0.57627119, 0.5       ],
       [0.33333333, 0.625     , 0.05084746, 0.04166667],
       [0.66666667, 0.45833333, 0.57627119, 0.54166667],
       [0.22222222, 0.58333333, 0.08474576, 0.04166667],
       [0.55555556, 0.33333333, 0.69491525, 0.58333333],
       [0.55555556, 0.58333333, 0.77966102, 0.95833333],
       [0.66666667, 0.54166667, 0.79661017, 0.83333333],
       [0.19444444, 0.625     , 0.05084746, 0.08333333],
       [0.36111111, 0.41666667, 0.52542373, 0.5       ],
       [0.38888889, 0.33333333, 0.59322034, 0.5       ],
       [0.16666667, 0.20833333, 0.59322034, 0.66666667],
       [0.36111111, 0.29166667, 0.54237288, 0.5       ],
       [0.13888889, 0.41666667, 0.06779661, 0.08333333],
       [0.55555556, 0.20833333, 0.6779661 , 0.75      ],
       [0.94444444, 0.25      , 1.        , 0.91666667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.19444444, 0.41666667, 0.10169492, 0.04166667],
       [0.19444444, 0.625     , 0.10169492, 0.20833333],
       [0.13888889, 0.58333333, 0.15254237, 0.04166667],
       [0.5       , 0.25      , 0.77966102, 0.54166667],
       [0.22222222, 0.75      , 0.15254237, 0.125     ],
       [0.47222222, 0.58333333, 0.59322034, 0.625     ],
       [0.47222222, 0.375     , 0.59322034, 0.58333333],
       [0.83333333, 0.375     , 0.89830508, 0.70833333],
       [0.41666667, 0.83333333, 0.03389831, 0.04166667],
       [0.72222222, 0.5       , 0.79661017, 0.91666667],
       [0.55555556, 0.29166667, 0.66101695, 0.70833333],
       [0.11111111, 0.5       , 0.10169492, 0.04166667],
       [0.61111111, 0.5       , 0.69491525, 0.79166667],
       [0.30555556, 0.41666667, 0.59322034, 0.58333333],
       [0.55555556, 0.20833333, 0.66101695, 0.58333333],
       [0.66666667, 0.54166667, 0.79661017, 1.        ],
       [0.22222222, 0.70833333, 0.08474576, 0.125     ],
       [0.36111111, 0.41666667, 0.59322034, 0.58333333],
       [0.19444444, 0.54166667, 0.06779661, 0.04166667],
       [0.66666667, 0.45833333, 0.77966102, 0.95833333],
       [0.75      , 0.5       , 0.62711864, 0.54166667],
       [0.5       , 0.33333333, 0.62711864, 0.45833333],
       [0.5       , 0.33333333, 0.50847458, 0.5       ],
       [0.58333333, 0.5       , 0.59322034, 0.58333333],
       [0.69444444, 0.33333333, 0.6440678 , 0.54166667],
       [0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.69444444, 0.41666667, 0.76271186, 0.83333333],
       [0.44444444, 0.41666667, 0.69491525, 0.70833333],
       [0.72222222, 0.45833333, 0.66101695, 0.58333333],
       [0.38888889, 1.        , 0.08474576, 0.125     ],
       [0.47222222, 0.41666667, 0.6440678 , 0.70833333],
       [0.30555556, 0.58333333, 0.08474576, 0.125     ],
       [0.47222222, 0.08333333, 0.6779661 , 0.58333333],
       [0.66666667, 0.45833333, 0.62711864, 0.58333333],
       [0.55555556, 0.375     , 0.77966102, 0.70833333],
       [0.25      , 0.875     , 0.08474576, 0.        ],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.44444444, 0.41666667, 0.54237288, 0.58333333],
       [0.22222222, 0.54166667, 0.11864407, 0.16666667],
       [0.19444444, 0.58333333, 0.10169492, 0.125     ],
       [0.91666667, 0.41666667, 0.94915254, 0.83333333],
       [0.61111111, 0.33333333, 0.61016949, 0.58333333],
       [0.52777778, 0.58333333, 0.74576271, 0.91666667],
       [0.66666667, 0.20833333, 0.81355932, 0.70833333],
       [0.38888889, 0.20833333, 0.6779661 , 0.79166667],
       [0.77777778, 0.41666667, 0.83050847, 0.83333333],
       [0.19444444, 0.125     , 0.38983051, 0.375     ],
       [0.44444444, 0.5       , 0.6440678 , 0.70833333],
       [0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.38888889, 0.41666667, 0.54237288, 0.45833333],
       [0.13888889, 0.45833333, 0.10169492, 0.04166667],
       [0.52777778, 0.33333333, 0.6440678 , 0.70833333],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.33333333, 0.16666667, 0.45762712, 0.375     ],
       [0.02777778, 0.41666667, 0.05084746, 0.04166667],
       [0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.58333333, 0.29166667, 0.72881356, 0.75      ],
       [0.5       , 0.41666667, 0.66101695, 0.70833333],
       [0.66666667, 0.41666667, 0.71186441, 0.91666667],
       [0.30555556, 0.58333333, 0.11864407, 0.04166667],
       [0.72222222, 0.45833333, 0.74576271, 0.83333333],
       [0.5       , 0.41666667, 0.61016949, 0.54166667],
       [0.61111111, 0.41666667, 0.71186441, 0.79166667],
       [0.22222222, 0.75      , 0.10169492, 0.04166667],
       [0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.41666667, 0.29166667, 0.69491525, 0.75      ],
       [0.19444444, 0.        , 0.42372881, 0.375     ],
       [0.25      , 0.625     , 0.08474576, 0.04166667],
       [0.16666667, 0.66666667, 0.06779661, 0.        ],
       [0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [1.        , 0.75      , 0.91525424, 0.79166667],
       [0.61111111, 0.41666667, 0.81355932, 0.875     ],
       [0.38888889, 0.33333333, 0.52542373, 0.5       ],
       [0.63888889, 0.375     , 0.61016949, 0.5       ],
       [0.02777778, 0.5       , 0.05084746, 0.04166667],
       [0.80555556, 0.66666667, 0.86440678, 1.        ],
       [0.08333333, 0.5       , 0.06779661, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.33333333, 0.91666667, 0.06779661, 0.04166667],
       [0.55555556, 0.54166667, 0.84745763, 1.        ],
       [0.80555556, 0.5       , 0.84745763, 0.70833333],
       [0.33333333, 0.16666667, 0.47457627, 0.41666667],
       [0.30555556, 0.79166667, 0.05084746, 0.125     ],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.38888889, 0.75      , 0.11864407, 0.08333333],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.58333333, 0.33333333, 0.77966102, 0.875     ],
       [0.16666667, 0.45833333, 0.08474576, 0.04166667],
       [0.69444444, 0.5       , 0.83050847, 0.91666667],
       [0.08333333, 0.66666667, 0.        , 0.04166667],
       [0.41666667, 0.29166667, 0.69491525, 0.75      ],
       [0.25      , 0.29166667, 0.49152542, 0.54166667],
       [0.27777778, 0.70833333, 0.08474576, 0.04166667],
       [0.33333333, 0.25      , 0.57627119, 0.45833333],
       [0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.22222222, 0.625     , 0.06779661, 0.08333333],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.36111111, 0.20833333, 0.49152542, 0.41666667],
       [0.72222222, 0.45833333, 0.69491525, 0.91666667],
       [0.33333333, 0.20833333, 0.50847458, 0.5       ],
       [0.80555556, 0.41666667, 0.81355932, 0.625     ],
       [0.19444444, 0.5       , 0.03389831, 0.04166667],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667]])

In [6]:
data=fetch_openml("car", as_frame=True).frame
data

c:\Users\limyt\OneDrive\Documents\VSCode\Scikit-learn\.venv-1\Lib\site-packages\sklearn\datasets\_openml.py:328: UserWarning: Multiple active versions of the dataset matching the name car exist. Versions may be fundamentally different, returning version 2. Available versions:
- version 2, status: active
  url: https://www.openml.org/search?type=data&id=991
- version 3, status: active
  url: https://www.openml.org/search?type=data&id=40975

  warn(warning_msg)

     buying  maint  doors persons lug_boot safety binaryClass
0     vhigh  vhigh      2       2    small    low           P
1     vhigh  vhigh      2       2    small    med           P
2     vhigh  vhigh      2       2    small   high           P
3     vhigh  vhigh      2       2      med    low           P
4     vhigh  vhigh      2       2      med    med           P
...     ...    ...    ...     ...      ...    ...         ...
1723    low    low  5more    more      med    med           N
1724    low    low  5more    more      med   high           N
1725    low    low  5more    more      big    low           P
1726    low    low  5more    more      big    med           N
1727    low    low  5more    more      big   high           N

[1728 rows x 7 columns]

In [ ]:
# ordinal encoder turn into numbers (that can fit machine algorithims)
columns_to_encode=["lug_boot", "safety"]

encoder=OrdinalEncoder(
    categories=[
        ["small", "med", "big"], 
        ["low", "med", "high"]
    ]
)

data[columns_to_encode]=encoder.fit_transform(data[columns_to_encode])
data

     buying  maint  doors persons  lug_boot  safety binaryClass
0     vhigh  vhigh      2       2       0.0     0.0           P
1     vhigh  vhigh      2       2       0.0     1.0           P
2     vhigh  vhigh      2       2       0.0     2.0           P
3     vhigh  vhigh      2       2       1.0     0.0           P
4     vhigh  vhigh      2       2       1.0     1.0           P
...     ...    ...    ...     ...       ...     ...         ...
1723    low    low  5more    more       1.0     1.0           N
1724    low    low  5more    more       1.0     2.0           N
1725    low    low  5more    more       2.0     0.0           P
1726    low    low  5more    more       2.0     1.0           N
1727    low    low  5more    more       2.0     2.0           N

[1728 rows x 7 columns]

In [ ]:
# one hot encoder turns multiple values for an individual feature into multiple columns that can be 0 or 1
data=fetch_openml("adult", as_frame=True).frame
data

c:\Users\limyt\OneDrive\Documents\VSCode\Scikit-learn\.venv-1\Lib\site-packages\sklearn\datasets\_openml.py:328: UserWarning: Multiple active versions of the dataset matching the name adult exist. Versions may be fundamentally different, returning version 1. Available versions:
- version 1, status: active
  url: https://www.openml.org/search?type=data&id=179
- version 2, status: active
  url: https://www.openml.org/search?type=data&id=1590

  warn(warning_msg)

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native-country,class
0,2,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,1,0,2,United-States,<=50K
1,3,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,0,United-States,<=50K
2,2,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,2,United-States,<=50K
3,3,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,2,United-States,<=50K
4,1,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,2,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,2,Private,215419,Bachelors,13,Divorced,Prof-specialty,Not-in-family,White,Female,0,0,2,United-States,<=50K
48838,4,NaN,321403,HS-grad,9,Widowed,NaN,Other-relative,Black,Male,0,0,2,United-States,<=50K
48839,2,Private,374983,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,3,United-States,<=50K
48840,2,Private,83891,Bachelors,13,Divorced,Adm-clerical,Own-child,Asian-Pac-Islander,Male,2,0,2,United-States,<=50K
48841,1,Self-emp-inc,182148,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,3,United-States,>50K

In [10]:
data.occupation.value_counts()

occupation
Prof-specialty       6172
Craft-repair         6112
Exec-managerial      6086
Adm-clerical         5611
Sales                5504
Other-service        4923
Machine-op-inspct    3022
Transport-moving     2355
Handlers-cleaners    2072
Farming-fishing      1490
Tech-support         1446
Protective-serv       983
Priv-house-serv       242
Armed-Forces           15
Name: count, dtype: int64

In [12]:
encoder=OneHotEncoder(handle_unknown="ignore", sparse_output=False)
encoded_value=encoder.fit_transform(data[["occupation", "race"]])
new_columns=encoder.get_feature_names_out(["occupation", "race"])

In [13]:
encoded_value

array([[1., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(48842, 20))

In [14]:
new_columns

array(['occupation_Adm-clerical', 'occupation_Armed-Forces',
       'occupation_Craft-repair', 'occupation_Exec-managerial',
       'occupation_Farming-fishing', 'occupation_Handlers-cleaners',
       'occupation_Machine-op-inspct', 'occupation_Other-service',
       'occupation_Priv-house-serv', 'occupation_Prof-specialty',
       'occupation_Protective-serv', 'occupation_Sales',
       'occupation_Tech-support', 'occupation_Transport-moving',
       'occupation_nan', 'race_Amer-Indian-Eskimo',
       'race_Asian-Pac-Islander', 'race_Black', 'race_Other',
       'race_White'], dtype=object)

In [15]:
df_encoded=pd.DataFrame(encoded_value, columns=new_columns, index=data.index)
data_final=pd.concat(
    [data.drop(columns=["occupation", "race"]), df_encoded], axis=1
)
data_final

,age,workclass,fnlwgt,education,education-num,marital-status,relationship,sex,capitalgain,capitalloss,...,occupation_Protective-serv,occupation_Sales,occupation_Tech-support,occupation_Transport-moving,occupation_nan,race_Amer-Indian-Eskimo,race_Asian-Pac-Islander,race_Black,race_Other,race_White
0,2,State-gov,77516,Bachelors,13,Never-married,Not-in-family,Male,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,3,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Husband,Male,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,2,Private,215646,HS-grad,9,Divorced,Not-in-family,Male,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,3,Private,234721,11th,7,Married-civ-spouse,Husband,Male,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,1,Private,338409,Bachelors,13,Married-civ-spouse,Wife,Female,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,2,Private,215419,Bachelors,13,Divorced,Not-in-family,Female,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
48838,4,NaN,321403,HS-grad,9,Widowed,Other-relative,Male,0,0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
48839,2,Private,374983,Bachelors,13,Married-civ-spouse,Husband,Male,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
48840,2,Private,83891,Bachelors,13,Divorced,Own-child,Male,2,0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
48841,1,Self-emp-inc,182148,Bachelors,13,Married-civ-spouse,Husband,Male,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0